#!/bin/bash
'''ENV string templates'''

HBNB_ENV = 'HBNB_ENV'
HBNB_MYSQL_USER = 'HBNB_MYSQL_USER'
HBNB_MYSQL_PWD = 'HBNB_MYSQL_PWD'
HBNB_MYSQL_HOST = 'HBNB_MYSQL_HOST'
HBNB_MYSQL_DB = 'HBNB_MYSQL_DB'
HBNB_TYPE_STORAGE = 'HBNB_TYPE_STORAGE'
DB = 'db'
FILE = 'file'
DEV = 'dev'
TEST = 'test'
